language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install .
  - pip install coveralls

script:
- coverage run -m unittest discover set_up_grasp_models/tests
- sh run_examples.sh

after_success: coveralls